// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: mms/pkg/proto/enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusUser int32

const (
	StatusUser_ACTIVE   StatusUser = 0
	StatusUser_INACTIVE StatusUser = 1
	StatusUser_DELETE   StatusUser = 2
)

// Enum value maps for StatusUser.
var (
	StatusUser_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
		2: "DELETE",
	}
	StatusUser_value = map[string]int32{
		"ACTIVE":   0,
		"INACTIVE": 1,
		"DELETE":   2,
	}
)

func (x StatusUser) Enum() *StatusUser {
	p := new(StatusUser)
	*p = x
	return p
}

func (x StatusUser) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusUser) Descriptor() protoreflect.EnumDescriptor {
	return file_mms_pkg_proto_enum_proto_enumTypes[0].Descriptor()
}

func (StatusUser) Type() protoreflect.EnumType {
	return &file_mms_pkg_proto_enum_proto_enumTypes[0]
}

func (x StatusUser) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusUser.Descriptor instead.
func (StatusUser) EnumDescriptor() ([]byte, []int) {
	return file_mms_pkg_proto_enum_proto_rawDescGZIP(), []int{0}
}

type Gender int32

const (
	Gender_UNKNOWN Gender = 0
	Gender_MALE    Gender = 1
	Gender_FEMALE  Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "UNKNOWN",
		1: "MALE",
		2: "FEMALE",
	}
	Gender_value = map[string]int32{
		"UNKNOWN": 0,
		"MALE":    1,
		"FEMALE":  2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_mms_pkg_proto_enum_proto_enumTypes[1].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_mms_pkg_proto_enum_proto_enumTypes[1]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_mms_pkg_proto_enum_proto_rawDescGZIP(), []int{1}
}

type Role int32

const (
	Role_CUSTOMER   Role = 0
	Role_EMPLOYEE   Role = 1
	Role_ADMIN      Role = 2
	Role_SUPERADMIN Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "CUSTOMER",
		1: "EMPLOYEE",
		2: "ADMIN",
		3: "SUPERADMIN",
	}
	Role_value = map[string]int32{
		"CUSTOMER":   0,
		"EMPLOYEE":   1,
		"ADMIN":      2,
		"SUPERADMIN": 3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_mms_pkg_proto_enum_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_mms_pkg_proto_enum_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_mms_pkg_proto_enum_proto_rawDescGZIP(), []int{2}
}

type Response int32

const (
	Response_OK    Response = 0
	Response_ERROR Response = 1
)

// Enum value maps for Response.
var (
	Response_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Response_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Response) Enum() *Response {
	p := new(Response)
	*p = x
	return p
}

func (x Response) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response) Descriptor() protoreflect.EnumDescriptor {
	return file_mms_pkg_proto_enum_proto_enumTypes[3].Descriptor()
}

func (Response) Type() protoreflect.EnumType {
	return &file_mms_pkg_proto_enum_proto_enumTypes[3]
}

func (x Response) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response.Descriptor instead.
func (Response) EnumDescriptor() ([]byte, []int) {
	return file_mms_pkg_proto_enum_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response Response `protobuf:"varint,1,opt,name=response,proto3,enum=pb.Response" json:"response,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_mms_pkg_proto_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mms_pkg_proto_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_mms_pkg_proto_enum_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetResponse() Response {
	if x != nil {
		return x.Response
	}
	return Response_OK
}

var File_mms_pkg_proto_enum_proto protoreflect.FileDescriptor

var file_mms_pkg_proto_enum_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x6d, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3a,
	0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x32, 0x0a, 0x0a, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49,
	0x56, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x2b,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x2a, 0x3d, 0x0a, 0x04, 0x52,
	0x6f, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x45, 0x52, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x4d, 0x50, 0x4c, 0x4f, 0x59, 0x45, 0x45, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x55,
	0x50, 0x45, 0x52, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x03, 0x2a, 0x1d, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mms_pkg_proto_enum_proto_rawDescOnce sync.Once
	file_mms_pkg_proto_enum_proto_rawDescData = file_mms_pkg_proto_enum_proto_rawDesc
)

func file_mms_pkg_proto_enum_proto_rawDescGZIP() []byte {
	file_mms_pkg_proto_enum_proto_rawDescOnce.Do(func() {
		file_mms_pkg_proto_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_mms_pkg_proto_enum_proto_rawDescData)
	})
	return file_mms_pkg_proto_enum_proto_rawDescData
}

var file_mms_pkg_proto_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mms_pkg_proto_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mms_pkg_proto_enum_proto_goTypes = []any{
	(StatusUser)(0),        // 0: pb.StatusUser
	(Gender)(0),            // 1: pb.Gender
	(Role)(0),              // 2: pb.Role
	(Response)(0),          // 3: pb.Response
	(*StatusResponse)(nil), // 4: pb.StatusResponse
}
var file_mms_pkg_proto_enum_proto_depIdxs = []int32{
	3, // 0: pb.StatusResponse.response:type_name -> pb.Response
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mms_pkg_proto_enum_proto_init() }
func file_mms_pkg_proto_enum_proto_init() {
	if File_mms_pkg_proto_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mms_pkg_proto_enum_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mms_pkg_proto_enum_proto_goTypes,
		DependencyIndexes: file_mms_pkg_proto_enum_proto_depIdxs,
		EnumInfos:         file_mms_pkg_proto_enum_proto_enumTypes,
		MessageInfos:      file_mms_pkg_proto_enum_proto_msgTypes,
	}.Build()
	File_mms_pkg_proto_enum_proto = out.File
	file_mms_pkg_proto_enum_proto_rawDesc = nil
	file_mms_pkg_proto_enum_proto_goTypes = nil
	file_mms_pkg_proto_enum_proto_depIdxs = nil
}
